### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Jotalz** [Jotalz/apex_dma_kvm_pub#12]
> > > > > > Can you be more specific about how to fix that, thank you
> > > > > 
> > > > > 
> > > > > Looks like you're missing something, try this: `sudo apt install clang` In addition, I don’t have the energy to update at the moment. You need to update the offset part yourself.
> > > > 
> > > > 
> > > > Thank you, I'm going to try your method, but I don't know how to update the offset part, is there a tutorial anywhere
> > > 
> > > 
> > > If you get the dump file(Text similar to offsets.txt in the project) by others, just read the Update OFFSETS section in readme.Then manually update the offset named HIGHLIGHT_SETTINGS in offsets.h,No matter how you get it.
> > 
> > 
> > Thank you for your reply. You are really a good person. Please allow me to express my gratitude. I really like you, but after following your instructions and installing the clang, it still prompts the same error.
> 
> What is the error reported this time? Have you installed all other Dependencies and RUST according to the tutorial?

Yes, I installed everything according to the prompts, but when I enter the/. build. sh command, an error message will appear
pdx@pdx-desktop :~/apexsky/apex_dma $/ Build.sh

+Set - eo pipefail

+Cargo -- version

Cargo 1.75.0

+++Dirname/ Build.sh

++CD

++Pwd

+SCRIPT-DIR=/home/pdx/apexsky/apex_dma

+BUILL_DIR=/home/pdx/apexsky/apex_dma/build

+Mkdir - p/home/pdx/apexsky/apex_dma/build

+Cd/home/pdx/apexsky/apex_dma/lib/memflow kvm

+Set+e

+Make

Touch "/home/pdx/apexsky/apex_dma/lib/memflow kvm/build/Makefile"

/Home/pdx/apexsky/apex_dma/lib/memflow kvm/build

Make C/lib/modules/6.2.0-39 generic/build M=/home/pdx/apexsky/apex_dma/lib/memflow kvm/build src=/home/pdx/apexsky/apex_dma/lib/memflow kvm/memflow kmod modules

Make [1]: Enter the directory "/usr/src/Linux headers 6.2.0-39 generic"

Warning: The compiler buffers from the one used to build the kernel

The kernel was built by: x86_64 Linux gnu gcc-11 (Ubuntu 11.4.0-1ubuntu1-22.04) 11.4.0

You are using: gcc-11 (Ubuntu 11.4.0-1ubuntu1-22.04) 11.4.0

Make [1]: Leave directory "/usr/src/Linux headers 6.2.0-39 generic"
Warning: The compiler buffers from the one used to build the kernel

The kernel was built by: x86_64 Linux gnu gcc-11 (Ubuntu 11.4.0-1ubuntu1-22.04) 11.4.0

You are using: gcc-11 (Ubuntu 11.4.0-1ubuntu1-22.04) 11.4.0

Make [1]: Leave directory "/usr/src/Linux headers 6.2.0-39 generic"

+Cp/home/pdx/apexsky/apex_dma/lib/memflow kvm/build/memflow.ko/home/pdx/apexsky/apex_dma/build/

+Set - e

+Cd/home/pdx/apexsky/apex_dma/apexsky

+Cargo build -- release

Warning: variant 'Reset' is not constructed

-->Src/menu/mod.rs: 43:5

|

37 | enum Message{

|------ variant in this enum

43 | Reset,

|^^^^^

|

=Note: ` # [warn (dead_code)] ` on by default

Warning: 'apexsky' (lib) generated 1 warning

Finished release [optimized] target (s) in 0.69s

+Cd/home/pdx/apexsky/apex_dma

+Cd/home/pdx/apexsky/apex_dma/build

+Cmake

--Including Wayland support

--Configuring done

--Generating done

--Build files have been written to:/home/pdx/apexsky/apex_dma/
+Cmake -- build

[1%] Performing build step for 'memflow'ffi'

CMake Error at/home/pdx/apexsky/apex_dma/build/memflowEffi prefix/src/memflowEffi stamp/memflowEffi build Release. cmake: 49 (message):

Command failed: 101

'cargo', 'build', 'release'

See also

/Home/pdx/apexsky/apex_dma/build/memflow_ffi prefix/src/memflow_ffi stamp/memflow_ffi build - *. log

Gmake [2]: * * * [MakeFiles/memflow_ffi. dir/build. make: 86: memflow_ffi prefix/src/memflow_ffi stamp/memflow_ffi build] Error 1

Gmake [1]: * * * [MakeFiles/Makefile2:881: CMakeFiles/memflow_ffi. dir/all] Error 2

Gmake: * * * [Makefile: 121: all] Error 2

_Originally posted by @dreambeaitbos in https://github.com/Jotalz/apex_dma_kvm_pub/issues/9#issuecomment-1980796184_

**Comment by Jotalz** [comment]
Please provide this file:
/Home/pdx/apexsky/apex_dma/build/memflow_ffi-prefix/src/memflow_ffi-stamp/memflow_ffi-build-err.log

**Comment by dreambeaitbos** [comment]
> Please provide this file: /Home/pdx/apexsky/apex_dma/build/memflow_ffi-prefix/src/memflow_ffi-stamp/memflow_ffi-build-err.log

   Updating git repository `https://github.com/h33p/goblin`
error: failed to load source for dependency `goblin`

Caused by:
  Unable to update https://github.com/h33p/goblin?branch=lossy-macho#4eefcf0a

Caused by:
  failed to fetch into: /home/pdx/.cargo/git/db/goblin-1ef241265c29c9b6

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  SSL error: unknown error; class=Ssl (16)

**Comment by dreambeaitbos** [comment]
> Oh, it seems the problem is with the network,try run`git submodule update --init --recursive` command under the apex_dma_kvm_pub folder,then try build again

Perhaps my network is not very good, thank you very much for your reply. I would like to ask, is it difficult to add a bullet tracking function?

**Comment by Jotalz** [comment]
> > Oh, it seems the problem is with the network,try run`git submodule update --init --recursive` command under the apex_dma_kvm_pub folder,then try build again
> 
> Perhaps my network is not very good, thank you very much for your reply. I would like to ask, is it difficult to add a bullet tracking function?

Actually I have never looked into this high risk feature, you may be able to learn about it on uc.There may be a data structure that stores the impact point of the bullet and can be modified to the location we want.
Did you resolve the compilation problem?

**Comment by dreambeaitbos** [comment]
> > > Oh, it seems the problem is with the network,try run`git submodule update --init --recursive` command under the apex_dma_kvm_pub folder,then try build again
> > 
> > 
> > Perhaps my network is not very good, thank you very much for your reply. I would like to ask, is it difficult to add a bullet tracking function?
> 
> Actually I have never looked into this high risk feature, you may be able to learn about it on uc.There may be a data structure that stores the impact point of the bullet and can be modified to the location we want. Did you resolve the compilation problem?

I think you are a very good person and I like you very much. Besides, I don't know much about this aspect. It would be better if you could give me some guidance when you are free, xD

**Comment by dreambeaitbos** [comment]
> > > Oh, it seems the problem is with the network,try run`git submodule update --init --recursive` command under the apex_dma_kvm_pub folder,then try build again
> > 
> > 
> > Perhaps my network is not very good, thank you very much for your reply. I would like to ask, is it difficult to add a bullet tracking function?
> 
> Actually I have never looked into this high risk feature, you may be able to learn about it on uc.There may be a data structure that stores the impact point of the bullet and can be modified to the location we want. Did you resolve the compilation problem?
In fact, I have finished compiling your version and can use it. The version that I failed to compile this time is chettoy's version. When I followed his steps, the bulid at the end would show an error, I don't know why.

**Comment by Jotalz** [comment]
Chettoy is a good guy too, my version is based entirely on a version of his,mainly in the use of some personal habits.
