### ISSUE TITLE
Offset update

### ISSUE THREAD

**Issue by pppaluarit** [Jotalz/apex_dma_kvm_pub#14]
update offset please

**Comment by dreambeaitbos** [comment]
> update offset please

namelist 0xC5E1150  highlightsettings 0xB944E30
This is the latest offset, can you guide me on what to update to be able to use in the new version of apex?

**Comment by Jotalz** [comment]
I just updated all the offsets, you guys can give it a try, not sure if there are any other changes, I really don't have time to focus on this
