### ISSUE TITLE
请求支援

### ISSUE THREAD

**Issue by mini120955** [Jotalz/apex_dma_kvm_pub#15]
你好大佬！能给我点帮助吗？我想知道您的项目中关于手柄模式的热键设置，我想修改一下但没找到，我想取消它的右键热键只保留左键。

**Comment by Jotalz** [comment]
locate [here](https://github.com/Jotalz/apex_dma_kvm_pub/blob/f83d57d63436b6ce281da55e35f3b5b2e0edf69e/apex_dma/apex_dma.cpp#L540),delete `zoom_state > 0`
