### ISSUE TITLE
 dma Windows

### ISSUE THREAD

**Issue by gaoyuxiang120** [Jotalz/apex_dma_kvm_pub#16]
hi, can this be used on my second windows pc with DMA linked to my game pc? 
idk how to run this stuff on windows. could anyone giveme some advice? 
use visual studio?or cmd directly
if it takes time, i can pay 50 CNY for it, if you anyone can make it work. thanks

**Comment by Jotalz** [comment]
chettoy's repo has already exists this version which named dam branch

**Comment by gaoyuxiang120** [comment]
Thank you for your reply! i found that branch, but i dont know how to run this thing on my second pc. run apex_dma.cpp? Do i need anything else like virtual studio to run it? My second pc is Windows. i really dont know how to make this thinng running. thank you for your help
