### ISSUE TITLE
求问

### ISSUE THREAD

**Issue by mini120955** [Jotalz/apex_dma_kvm_pub#17]
您好Jotalz，如果不使用覆盖能否实现小地图呢？

**Comment by Jotalz** [comment]
如果游戏本身存在小地图中显示敌方信息的做法，那么理论上不依赖外部绘制也可能实现，但是目前还没看到过这种做法。

**Comment by mini120955** [comment]
将覆盖中的雷达功能单独剥离出来，通过局域网将实时的雷达数据发送给虚拟机，在虚拟机中对雷达数据进行处理，从而在虚拟机中通过外部绘制实现雷达是否可行呢？如果您觉得可行的话，能否告诉我您的雷达功能代码位置吗，我想尝试实现一下，我的电脑用looking glass不够流畅，但又特别想用这个功能😛

**Comment by mini120955** [comment]
将覆盖中的雷达功能单独分割出来，通过中继将实时的雷达数据发送给虚拟机，在虚拟机中对雷达数据进行处理，从而在虚拟机中通过外部较差现实雷达是否可以可行性呢？如果您觉得可行能否告诉我您的雷达功能后代码位置吗，我想尝试实现，我的电脑看起来不够流畅，但又特别想使用这个功能😛




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月11日(周一) 下午4:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jotalz/apex_dma_kvm_pub] 求问 (Issue #17)




 
如果游戏本身存在小地图中显示敌方信息的做法，那么理论上不依赖外部绘制也可能实现，但是目前还没看到过这种做法。

**Comment by Jotalz** [comment]
[大地图雷达](https://github.com/Jotalz/apex_dma_kvm_pub/blob/f83d57d63436b6ce281da55e35f3b5b2e0edf69e/apex_dma/Client/main.cpp#L637)
