### ISSUE TITLE
[SOLVED] Got a error when build about not support that cpu not support AVX2 tech

### ISSUE THREAD

**Issue by BoheSama1999** [Jotalz/apex_dma_kvm_pub#19]
### **System Platform :**
System Archlinux x86_64 6.8.1-arch1-1
CPU Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
GPU NVIDIA GeForce GTX 1060 3GB
Memory 32015MiB

### **What happend when build :**
When i build in linux with command
`./build.sh`
it got errors
Here about the error:
`/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include/avx2intrin.h:913:1: error: inlining failed in call to ‘always_inline’ ‘__m256i _mm256_xor_si256(__m256i, __m256i)’: target specific option mismatch
  913 | _mm256_xor_si256 (__m256i __A, __m256i __B)
      | ^~~~~~~~~~~~~~~~
/home/BoheSama/vmread/apex_dma_kvm_pub/apex_dma/Client/impl/libraries/xor/xorstr.hpp:211:48: note: called from here
  211 |             ((Indices >= sizeof(_storage) / 32 ? static_cast<void>(0) : _mm256_store_si256(
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  212 |                 reinterpret_cast<__m256i*>(_storage) + Indices,
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  213 |                 _mm256_xor_si256(
      |                 ~~~~~~~~~~~~~~~~~               
  214 |                     _mm256_load_si256(reinterpret_cast<const __m256i*>(_storage) + Indices),
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  215 |                     _mm256_load_si256(reinterpret_cast<const __m256i*>(keys) + Indices)))), ...);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include/avx2intrin.h:913:1: error: inlining failed in call to ‘always_inline’ ‘__m256i _mm256_xor_si256(__m256i, __m256i)’: target specific option mismatch
  913 | _mm256_xor_si256 (__m256i __A, __m256i __B)
      | ^~~~~~~~~~~~~~~~
/home/BoheSama/vmread/apex_dma_kvm_pub/apex_dma/Client/impl/libraries/xor/xorstr.hpp:211:48: note: called from here
  211 |             ((Indices >= sizeof(_storage) / 32 ? static_cast<void>(0) : _mm256_store_si256(
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  212 |                 reinterpret_cast<__m256i*>(_storage) + Indices,
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  213 |                 _mm256_xor_si256(
      |                 ~~~~~~~~~~~~~~~~~               
  214 |                     _mm256_load_si256(reinterpret_cast<const __m256i*>(_storage) + Indices),
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  215 |                     _mm256_load_si256(reinterpret_cast<const __m256i*>(keys) + Indices)))), ...);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/apex_dma.dir/build.make:160: CMakeFiles/apex_dma.dir/Client/overlay.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:990: CMakeFiles/apex_dma.dir/all] Error 2
make: *** [Makefile:121: all] Error 2
`
**### How i solved?**

First at all
THE WAY TO SOLV THE PROBLEM IS ADD `#define JM_XORSTR_DISABLE_AVX_INTRINSICS` in xorstr.hpp

I checked the` _mm256_store_si256` in [_Intel® Intrinsics Guide_](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html)  

Found that it is use AVX2 technology
Then i try to find some way to disable or replace a way to realize it

I try to search the error information in google,but i find someway that cannot be solved 
And finally i found the [xorstr git](https://github.com/JustasMasiulis/xorstr) 

```
supported compilers and platforms
Tested to be working on clang 5.0+, gcc 7.1+ and MSVC v141. If your CPU does not support AVX define JM_XORSTR_DISABLE_AVX_INTRINSICS to only use SSE.
```

**Comment by Jotalz** [comment]
terrible,idk how to fix it

**Comment by Jotalz** [comment]
I read your post carefully again today,you're doing great.(^_^)

**Comment by BoheSama1999** [comment]
> I read your post carefully again today,you're doing great.(^_^)

Thank you ＜3
