### ISSUE TITLE
Can you please check the error?

### ISSUE THREAD

**Issue by surreal4578** [Jotalz/apex_dma_kvm_pub#21]
![image](https://github.com/Jotalz/apex_dma_kvm_pub/assets/164652792/25478d03-5463-4ad6-91b7-1871c918582f)

I compiled and ran it as per your guide

[ERROR] connector: unable to read memory
Unable to initialize kvm connector.
Fallback to qemu connector.

I get this error in the middle, but I'm not sure what it is.
If you have time, I would appreciate your help.

**Comment by Jotalz** [comment]
did you use `su`,and then `./apex_dma`?

**Comment by surreal4578** [comment]
Sir. If you have a moment, would you mind DMing me on Discord?

discord name : kakao112

**Comment by Jotalz** [comment]
Try the following:


> Sir. If you have a moment, would you mind DMing me on Discord?
> 
> discord name : kakao112
Do you have other error logs?I can't determine the problem,but a possible suggestion is to recompile using the following directive
```
git clone --recurse https://github.com/Jotalz/apex_dma_kvm_pub
cd apex_dma
git submodule update --init --recursive
cd apex_dma
./build.sh
```

**Comment by surreal4578** [comment]
> 다음을 시도해 보세요:
> 
> > 선생님. 잠시 시간을 내어 Discord에서 제게 DM을 보내주시겠어요?
> > 디스코드 이름 : kakao112 
> > 다른 오류 로그가 있습니까?문제를 확인할 수는 없지만 다음 지시문을 사용하여 다시 컴파일하는 것이 좋습니다.
> 
> ```
> git clone --recurse https://github.com/Jotalz/apex_dma_kvm_pub
> cd apex_dma
> git submodule update --init --recursive
> cd apex_dma
> ./build.sh
> ```

Still have the same error......
Help me sir,,,,,,,

**Comment by Jotalz** [comment]
It show that `connector: unable to read memory`.If the permissions are sufficient I‘m no more idea for this,sry,may be you can try cheotty's repo to see if you have the same problem.

**Comment by surreal4578** [comment]
> It show that `connector: unable to read memory`.If the permissions are sufficient I‘m no more idea for this,sry,may be you can try cheotty's repo to see if you have the same problem.

No errors occurred when I compiled and ran chettoy's data.
I will enable full permissions using the chmod -R 777 command and try again.

**Comment by Jotalz** [comment]
You can try switching to the root account to execute

**Comment by surreal4578** [comment]
I was stupid. There was no need to compile
Because you have already uploaded the file to Actions.

**Comment by surreal4578** [comment]
![image](https://github.com/Jotalz/apex_dma_kvm_pub/assets/164652792/dd1d6a5f-b98e-4d6a-91b6-bf44c8066496)

By the way, there are 4 actions over 3 days.
Can I use the most recent one?
Do you upload an action every time you fix a bug?

**Comment by Jotalz** [comment]
Updated with game updates.You should use the latest version

**Comment by surreal4578** [comment]
> Updated with game updates.You should use the latest version

![image](https://github.com/Jotalz/apex_dma_kvm_pub/assets/164652792/376cd3fe-e4b0-4036-952b-40491d134ef7)

I'm sorry for bothering you with questions.

Should I run this command on my host (ubuntu)? Or should I run it in guest (windows)?

**Comment by Jotalz** [comment]
no

**Comment by surreal4578** [comment]
> no

Are you saying to run it on Windows?

**Comment by Jotalz** [comment]
This is for the day when I won’t update this repo. You can update the offsets by yourself.

**Comment by surreal4578** [comment]
> This is for the day when I won’t update this repo. You can update the offsets by yourself.

Since you might be late because something comes up, I want to know in advance how to update the offset myself.
