### ISSUE TITLE
How to turn on/off aimbot manually in this verison?

### ISSUE THREAD

**Issue by Alexxweiadyre** [Jotalz/apex_dma_kvm_pub#22]
Hello Jotalz, your project version is amazing, but I wondering how to turn on/off aimbot manually just like chettoy's version? In your version, It seems like the aimbot is turning on all the time. How to turn it off manually? Thank you!

**Comment by Jotalz** [comment]
Just to set hotkeys other than the left and right button,Release the aim-bot key when you won't use it.

**Comment by Jotalz** [comment]
It's also fairly easy to add an extra switch,see [this] line(https://github.com/Jotalz/apex_dma_kvm_pub/blob/773323de1653513b6b1ab403df09727a01a089d6/apex_dma/apex_dma.cpp#L525)
add a setting like ` if (g_settings.keyboard && g_settings.aim_on) { ` add this item accordingly in other files and you're done.Same goes for pad settings.But I'm not planning to add it yet.
