### ISSUE TITLE
Can you tell me how to update the offset?

### ISSUE THREAD

**Issue by surreal4578** [Jotalz/apex_dma_kvm_pub#23]
![image](https://github.com/Jotalz/apex_dma_kvm_pub/assets/164652792/4fd104a4-b10e-4e7f-a075-748c49025dd1)

As you can see in the picture, someone at unknown cheat shared the offset.
Can you tell me in detail what to do to modify your offset?
I'm not good at English because it's not my native language thank you

**Comment by Jotalz** [comment]
New offsets pushed.
