### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by surreal4578** [Jotalz/apex_dma_kvm_pub#24]
Glow is visible only up to about 200m.
can you please fix this

**Comment by Jotalz** [comment]
Added to dev branch, please try it out and give feedback.

**Comment by surreal4578** [comment]
![image](https://github.com/Jotalz/apex_dma_kvm_pub/assets/164652792/691d2af3-04ac-4095-826b-5b22ac1657ea)

Thanks for adding the glow distance but  player glow doesn't work
Item glow still works fine
T.T..........
