### ISSUE TITLE
player glow

### ISSUE THREAD

**Issue by surreal4578** [Jotalz/apex_dma_kvm_pub#26]
![image](https://github.com/Jotalz/apex_dma_kvm_pub/assets/164652792/35bb76b7-eea3-4ca7-acb3-0eead715b816)

Thanks for adding glow distance. But the player glow doesn't work.
Item glow still works fine
T.T.......

**Comment by surreal4578** [comment]
The player glow distance is fixed at 10m.

**Comment by Jotalz** [comment]
oh,sry,i'm made a mistake,ahhhh,fix later...

**Comment by surreal4578** [comment]
> oh,sry,i'm made a mistake,ahhhh,fix later...

Please tell me what part needs to be fixed and I will do it myself.

**Comment by Jotalz** [comment]
> > oh,sry,i'm made a mistake,ahhhh,fix later...
> 
> Please tell me what part needs to be fixed and I will do it myself.

Fixed already

**Comment by surreal4578** [comment]
> > > oh,sry,i'm made a mistake,ahhhh,fix later...
> > 
> > 
> > Please tell me what part needs to be fixed and I will do it myself.
> 
> Fixed already

Thank you for your kindness
