### ISSUE TITLE
How to update Glow

### ISSUE THREAD

**Issue by pppaluarit** [Jotalz/apex_dma_kvm_pub#30]
i updated offset using python scripts in the description, everything seems work except for glow

**Comment by pppaluarit** [comment]
yes, need to update this #define HIGHLIGHT_SETTINGS 0xBB247D0 //updated 2024/04/09 HighlightSettings manually

**Comment by Jotalz** [comment]
Yes, I have prompts for non-existing offsets and unrecognized offsets in the file in the update script.
Some of them you need to update manually.

**Comment by pppaluarit** [comment]
ahh ok tysm
