### ISSUE TITLE
help

### ISSUE THREAD

**Issue by pppaluarit** [Jotalz/apex_dma_kvm_pub#35]
i reinstall my os and get this build error: 
error[E0308]: mismatched types
   --> /home/munf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-wasix-0.18.3/src/runtime/package_loader/load_package_tree.rs:353:65
    |
353 |             MappedPathFileSystem::new(WebcVolumeFileSystem::new(volume.clone()), move |path| {
    |                                       ------------------------- ^^^^^^^^^^^^^^ expected `webc::volume::Volume`, found `webc::Volume`
    |                                       |
    |                                       arguments to this function are incorrect
    |
    = note: `webc::Volume` and `webc::volume::Volume` have similar names, but are actually distinct types
note: `webc::Volume` is defined in crate `webc`
   --> /home/munf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webc-5.8.1/src/volume.rs:79:1
    |
79  | pub struct Volume {
    | ^^^^^^^^^^^^^^^^^
note: `webc::volume::Volume` is defined in crate `webc`
   --> /home/munf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webc-6.0.0-alpha6/src/volume.rs:98:1
    |
98  | pub struct Volume {
    | ^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `webc` are being used?
note: associated function defined here
   --> /home/munf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/virtual-fs-0.11.3/src/webc_volume_fs.rs:28:12
    |
28  |     pub fn new(volume: Volume) -> Self {
    |            ^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `wasmer-wasix` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

help

**Comment by Jotalz** [comment]
I think this is due to a dependency version compatibility,you can try run `cargo update -p wasmer-wasix` under `apex_dma/apexsky/`
directory and recompile

**Comment by pppaluarit** [comment]
thanks it solved.

**Comment by pppaluarit** [comment]
now apex cant be played in vm, how to bypass the detection?

**Comment by Jotalz** [comment]
> now apex cant be played in vm, how to bypass the detection?

I‘m no idea now,Maybe someone will give a way, maybe it will become history

**Comment by Jotalz** [comment]
> now apex cant be played in vm, how to bypass the detection?

Try  to do QEMU-bypass, it should work

**Comment by pppaluarit** [comment]
is your kvm using dual gpu passthrough or single one bro?

**Comment by Jotalz** [comment]
single
