### ISSUE TITLE
wanna ask new apex vm detection thing

### ISSUE THREAD

**Issue by pppaluarit** [Jotalz/apex_dma_kvm_pub#36]
i can start apex with just edit the xml with my hardware info, should i using qemu bypass or just edit the xml?
which one is safer in your opinion, thx

**Comment by Jotalz** [comment]
Preferably a complete Spoofing, but I think it's enough to be playable

**Comment by Jotalz** [comment]
Is the problem you mentioned before only solved by using `cargo update -p wasmer-wasix`? Another person also had this problem, but he said that this method did not work for him.

**Comment by pppaluarit** [comment]
i also change something in Cargo.toml
wait i'll look for it

**Comment by pppaluarit** [comment]
in Cargo.toml
i add this 
virtual-fs = { version = "=0.11.1", optional = true } to [dependencies]
and this 
wasmer = ["dep:wasmer", "dep:virtual-fs", "dep:wasmer-wasix"] in [features]

**Comment by pppaluarit** [comment]
i change Cargo.toml in this folder
/apex_dma_kvm_pub/apex_dma/apexsky/

**Comment by Jotalz** [comment]
Thank you! it's effective,Where did you get this solution?

**Comment by Jotalz** [comment]
wow,I thought it would be difficult to solve this kind of problem,but it did it.
