### ISSUE TITLE
about cr3 decrypt

### ISSUE THREAD

**Issue by pppaluarit** [Jotalz/apex_dma_kvm_pub#37]
help 
how to add this [vmmdll.txt](https://github.com/Jotalz/apex_dma_kvm_pub/files/15281724/vmmdll.txt) in your project, i got this from chatgpt by convert mem search in apex_dma.cpp to mem search using vmmdll since it needed to bypass cr3 decrypt. but since im dumb, i dont know how to implement this, you can find vmm in the MemProcfs api: https://github.com/ufrisk/MemProcFS
hope you can implement this

**Comment by Jotalz** [comment]
Tired,give me time to rest😂,maybe solve it tomorrow

**Comment by pppaluarit** [comment]
okay take your time
