### ISSUE TITLE
It's updated today~ It's not very usable

### ISSUE THREAD

**Issue by zzy25w** [Jotalz/apex_dma_kvm_pub#41]
New update on 5.22

**Comment by zzy25w** [comment]
thank you

**Comment by Jotalz** [comment]
itemglow is it effective？I haven't made it controllable since the last update,The gold seems to no longer glow

**Comment by zzy25w** [comment]
> itemglow有效吗？自从上次更新以来，我就没有让它可控了，金色似乎不再发光了
It has no effect, and now both the glow and self-aim are ineffective

**Comment by Jotalz** [comment]
This is not what is expected to happen, try going back to the previous [version](https://github.com/Jotalz/apex_dma_kvm_pub/commit/78eced0cdd9b331cb50ac584dc94283188ede97d) to check if it works.

**Comment by zzy25w** [comment]
It's really a bad news, just updated still can't be used, the character glow and automatic aiming still have no effect, but the item glow appears without a choice

**Comment by Jotalz** [comment]
There should be no problem with Aimbot now. but the item glow needs further exploration.

**Comment by zzy25w** [comment]
Thank you! You are my God
