### ISSUE TITLE
How to turn off weaponheld glow?

### ISSUE THREAD

**Issue by pppaluarit** [Jotalz/apex_dma_kvm_pub#42]
![Untitled](https://github.com/Jotalz/apex_dma_kvm_pub/assets/158227234/ab190189-01d7-4781-bfdb-eb0276cf6b4f)

**Comment by Jotalz** [comment]
Don't want to care about it for now,just treat this color as the default.

**Comment by Jotalz** [comment]
Or don't turn on spectating weapon glow.

**Comment by pppaluarit** [comment]
thanks, i will try it
