### ISSUE TITLE
How to build an usable  ESP client ?

### ISSUE THREAD

**Issue by Harvey518** [Jotalz/apex_dma_kvm_pub#44]
Hello, it looks like you've only show how to build an apex_dma,.How can I build an ESP client.exe? g++ with apex_dma/Client/main.cpp? 

Looking forward to your reply !
Thank you very much!
Have a good day

**Comment by Jotalz** [comment]
in `apex_dma.cpp`,`static void EspLoop()`,change `esp_t = false; ` to `esp_t = true;` and then rebuild it.You should be able to enable the overlay feature in the tui settings.But, since I only have a single gpu,the overlay part has not been maintained, so it is likely that it will not work well.
