### ISSUE TITLE
Some running error

### ISSUE THREAD

**Issue by Harvey518** [Jotalz/apex_dma_kvm_pub#45]
Hey Hi!
I build this successfully  but can't run it. Here is the log 

04:35:55 [ERROR] connector: unable to read memory (Could not access the memflow device at /dev/memflow. Please make sure that you installed the dkms module properly and that it is loaded via `modprobe memflow`. Also ensure that you have read and write access to /dev/memflow. For further information check the readme at https://github.com/memflow/memflow-kvm)
04:35:55 [ERROR] connector: unable to read memory

How can I solve this problem?
thx for your reply!
![error](https://github.com/user-attachments/assets/285572a1-1000-4ded-b3f0-a4eae008cbe3)

**Comment by Jotalz** [comment]
Normal output, does not affect use
