### ISSUE TITLE
Cannot open the overlay.

### ISSUE THREAD

**Issue by silenthhk** [Jotalz/apex_dma_kvm_pub#46]
Open it and report an error. The mistake is falied to initiialize opengl loader

**Comment by Jotalz** [comment]
try to edit in `apex_dma.cpp`,`static void EspLoop()`,change `esp_t = false`;  to `esp_t = true;`
By the way,I have never used the overlay feature(single gpu), so I have basically not maintained it.So even if it doesn't work, it's probably normal.
You can also try apexsky by chettoy

**Comment by silenthhk** [comment]
ok
