### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by jojxx** [Jotalz/apex_dma_kvm_pub#48]
update actions pleas

**Comment by Jotalz** [comment]
There will be an important update today,  will push it together later.

**Comment by jojxx** [comment]
> There will be an important update today, will push it together later.

**i try update but  i have problem** with build [ 17%] No configure step for 'memflow_kvm'
[ 19%] Performing build step for 'memflow_kvm'
CMake Error at /home/tvx/intel/apex_dma_kvm_pub/apex_dma/build/memflow_kvm-prefix/src/memflow_kvm-stamp/memflow_kvm-build-Release.cmake:49 (message):
  Command failed: 101

   'cargo' 'build' '--release' '--all-features'

  See also

    /home/tvx/intel/apex_dma_kvm_pub/apex_dma/build/memflow_kvm-prefix/src/memflow_kvm-stamp/memflow_kvm-build-*.log


make[2]: *** [CMakeFiles/memflow_kvm.dir/build.make:86: memflow_kvm-prefix/src/memflow_kvm-stamp/memflow_kvm-build] Error 1
make[1]: *** [CMakeFiles/Makefile2:907: CMakeFiles/memflow_kvm.dir/all] Error 2
make: *** [Makefile:121: all] Error 2

**Comment by Jotalz** [comment]
please send me this file: `/home/tvx/intel/apex_dma_kvm_pub/apex_dma/build/memflow_kvm-prefix/src/memflow_kvm-stamp/memflow_kvm-build-err.log`

**Comment by jojxx** [comment]
> please send me this file: `/home/tvx/intel/apex_dma_kvm_pub/apex_dma/build/memflow_kvm-prefix/src/memflow_kvm-stamp/memflow_kvm-build-err.log`
[memflow_kvm-build-err.log](https://github.com/user-attachments/files/17036538/memflow_kvm-build-err.log)

**Comment by Jotalz** [comment]
Thank you for the information,this error is caused by the fact that the function has been deleted in the new version, resulting in a compilation error. Currently, you can choose to reduce the rust version to 1.75 to solve this problem.I'll think of a better way to solve this problem sometime.

**Comment by Jotalz** [comment]
updated
