### ISSUE TITLE
silent-aim 

### ISSUE THREAD

**Issue by xzen111** [Jotalz/apex_dma_kvm_pub#49]
silent aim still work ?

**Comment by Jotalz** [comment]
not added

**Comment by xzen111** [comment]
> not added



> not added

alright i test today ur build everything good just one thing about triggerbot on wingman not work maybe ID weapon ?

**Comment by Jotalz** [comment]
Will fix it later

**Comment by xzen111** [comment]
> Will fix it later

ty sir for build y have hard work <3

**Comment by Jotalz** [comment]
Thanks,fixed already,have a good time:)

**Comment by xzen111** [comment]
> Thanks,fixed already,have a good time:)

great i will test again

**Comment by xzen111** [comment]
build Unfinished again ?

**Comment by Jotalz** [comment]
It does not affect the use, just writing a function to help get the item ID

**Comment by xzen111** [comment]
manual update just Localplayer and Glow setting  fix type ect.... !!

**Comment by Jotalz** [comment]
Try it,It should be OK

**Comment by xxZENxxx** [comment]
> Try it,It should be OK

yeap work just i mean with Update.py 
onething what u mean smooth_sub minimum  85 m no beaming if close ? aimbot feel like  smooth legit
