### ISSUE TITLE
Weapon model glow and spectated indicator

### ISSUE THREAD

**Issue by Harvey518** [Jotalz/apex_dma_kvm_pub#51]
This feature still able to use?
It seems no glow on weapon model all the game time.(already turn on this feature )

**Comment by Jotalz** [comment]
I haven't tried it after the latest version update, there may be offset errors, but the function is valid.

**Comment by Jotalz** [comment]
> This feature still able to use?
> It seems no glow on weapon model all the game time.(already turn on this feature )
After trying，it works fine.
