### ISSUE TITLE
Merge Dev to Main 

### ISSUE THREAD

**Issue by xxZENxxx** [Jotalz/apex_dma_kvm_pub#52]
last Merge Dev to Main   issue aimbot trigger bot some time not working and FORWARD button when shoot  cant be move i cant back old src wass fine ( yes last offset) nvm i will force this branch 707cae9

**Comment by Jotalz** [comment]
Do you mean d84191b0f75ade96a3b198a5495d735aa810fea3 has a problem, but 707cae9 has no problem? The trigger is the same in both versions, I just fixed the bug that Flick was affected by the trigger toggle.So, sometimes not working may be due to a defect in the trigger itself.If I come up with a better algorithm, I will improve it.

> FORWARD button when shoot cant be move

Under what specific conditions does it occur? Is it common? I hadn't noticed this, thanks for your feedback.

**Comment by xxZENxxx** [comment]
> Do you mean [d84191b](https://github.com/Jotalz/apex_dma_kvm_pub/commit/d84191b0f75ade96a3b198a5495d735aa810fea3) has a problem, but [707cae9](https://github.com/Jotalz/apex_dma_kvm_pub/commit/707cae9b7053624f9ddd96d2af7dae9ab742b315) has no problem? The trigger is the same in both versions, I just fixed the bug that Flick was affected by the trigger toggle.So, sometimes not working may be due to a defect in the trigger itself.If I come up with a better algorithm, I will improve it.
> 
> > FORWARD button when shoot cant be move
> 
> Under what specific conditions does it occur? Is it common? I hadn't noticed this, thanks for your feedback.

i update  rn 707cae9  no any problem all work fine but ur last version not noly trugger also aimbot work like 5 sec and stop not work anymore on left click and right click i test this on firerange and bot match and FORWARD  sometime i need duble click to move

**Comment by xxZENxxx** [comment]
git branch   707cae9  useful

**Comment by Jotalz** [comment]
> but ur last version not only trigger also aimbot work like 5 sec and stop not work anymore

Do you mean the latest version of the main branch or the dev branch?

**Comment by xxZENxxx** [comment]
> > but ur last version not only trigger also aimbot work like 5 sec and stop not work anymore
> 
> Do you mean the latest version of the main branch or the dev branch?

not dev  i mean Main branch u can check it aimbot not work everytime and trigger tomorrow  i will ckeck again

**Comment by Jotalz** [comment]
> > > but ur last version not only trigger also aimbot work like 5 sec and stop not work anymore
> > 
> > 
> > Do you mean the latest version of the main branch or the dev branch?
> 
> not dev i mean Main branch u can check it aimbot not work everytime and trigger tomorrow i will ckeck again

That sounds terrible, I'll check it out when I have time.

**Comment by xxZENxxx** [comment]
> > > > but ur last version not only trigger also aimbot work like 5 sec and stop not work anymore
> > > 
> > > 
> > > Do you mean the latest version of the main branch or the dev branch?
> > 
> > 
> > not dev i mean Main branch u can check it aimbot not work everytime and trigger tomorrow i will ckeck again
> 
> That sounds terrible, I'll check it out when I have time.

not dev i mean Main branch u can check it aimbot work only one time when pree shiift but when swith key 109 or 108 stop working

**Comment by Jotalz** [comment]
Have you turned on Recoil reduction? In the latest main branch, Recoil reduction mode will turn off aiming, they are mutually exclusive.
Recoil reduction ON -> Aimbot and trigger OFF
Recoil reduction OFF -> Aimbot ON

**Comment by xxZENxxx** [comment]
> Have you turned on Recoil reduction? In the latest main branch, Recoil reduction mode will turn off aiming, they are mutually exclusive. Recoil reduction ON -> Aimbot and trigger OFF Recoil reduction OFF -> Aimbot ON

ready OFF  just aimbot Sometimes it doesn't respond  
idk ur last update fix issue ?

**Comment by xxZENxxx** [comment]
a friend test last update same problem maybe u have issue in visible time idk

**Comment by Jotalz** [comment]
It should be fine now.

**Comment by xxZENxxx** [comment]
> It should be fine now.

yeap work perfect <3 i will try fix skynade on ads

**Comment by Jotalz** [comment]
what's the matter in skynade?

**Comment by xxZENxxx** [comment]
> what's the matter in skynade?

cant be use hold right click. work just on active no ads if u loot  grnd first  u dead XD  cant be control camera

**Comment by Jotalz** [comment]
This is a really weird problem, it works perfectly fine on my computer,but in my friend has the same as you,I printed the heldid on his computer and it was the wrong value,about -60000,you know -251 is correct.
I suspect it's a thread safety issue, so I use a safer way to use global variables in the dev branch. You can try it to see if there is any problem.

**Comment by xxZENxxx** [comment]
ok sir i will ty mutex  for thread safety like`std::mutex mtx; 
int heldID = -251;`
