### ISSUE TITLE
shooting range mode

### ISSUE THREAD

**Issue by Harvey518** [Jotalz/apex_dma_kvm_pub#55]
where can I find the shooting range mode so I can know if aimbot is still working.
It seems like the newest commit build’s aimbot can’t work on my computer.

**Comment by Jotalz** [comment]
In fact, both the fire range and team modes have been changed to automatic switching,and it works fine on my computer.I'm not sure what causes some people to malfunction.
- If possible,you can add printf("..."); at the necessary places in the function to observe what happens and then give me feedback.

By the way, try deleting setting.toml and DTB.txt and re-running

**Comment by Jotalz** [comment]
a demo in Main branch `Pictures/demo.mp4`

**Comment by Harvey518** [comment]
thx I'll try it

**Comment by Harvey518** [comment]
I find it. test in fire range
when using the recoil reduce the aimbot shut down in fire range.

**Comment by Jotalz** [comment]
It is designed to be mutually exclusive,[here](https://github.com/Jotalz/apex_dma_kvm_pub/blob/4fe7c3f49dc4e8cf0b80425c4492d96a3cb74d55/apex_dma/apexsky/src/menu/apex_menu.rs#L798)
And any wrong with the skynade?

**Comment by Harvey518** [comment]
according to the code. there is no wrong.
is that means I can only choose one of them(aimbot, recoil reduce) to use?

**Comment by Jotalz** [comment]
Yes, the single recoil reduce is for more legal gaming.Of course you can modify it, but I think the recoil reduce will interfere with the calculation of the aimbot

**Comment by Harvey518** [comment]
OK i know it thx
