### ISSUE TITLE
new offset please

### ISSUE THREAD

**Issue by fastmatikqcc** [Jotalz/apex_dma_kvm_pub#57]

**Comment by fastmatikqcc** [comment]
https://github.com/fastmatikqcc/Apex_Offsets/blob/main/apex_offset.h

**Comment by xxZENxxx** [comment]
> https://github.com/fastmatikqcc/Apex_Offsets/blob/main/apex_offset.h

we shold be fix  CR3 first

**Comment by Jotalz** [comment]
> _No description provided._

Currently only [release](https://github.com/Jotalz/apex_dma_kvm_pub/releases/download/v3.0.1.16/build.zip) versions are available
