### ISSUE TITLE
Repo update

### ISSUE THREAD

**Issue by Feilink1** [Jotalz/apex_dma_kvm_pub#58]
@Jotalz Hi,  is there an ETA to when the repo would be updated to latest patch ? I have not been able to use it for months now. Thank you in advance, Regards

**Comment by Feilink1** [comment]
Actually regarding the latest release I think the source zip is not the same as the build zip, when I build the source and run it it keeps checking for new DTB every 5 secs so it's not really fixed, whereas the build zip works just fine. Could you please update the source as well ?

**Comment by xxZENxxx** [comment]
> Actually regarding the latest release I think the source zip is not the same as the build zip, when I build the source and run it it keeps checking for new DTB every 5 secs so it's not really fixed, whereas the build zip works just fine. Could you please update the source as well ?

 we dont update repo for some reason security  method  we can update build late

**Comment by Feilink1** [comment]
Many features don't work properly. Can I talk to the owner @Jotalz does he have a discord ?

**Comment by Feilink1** [comment]
What security reasons ? the fix is already available in UC ...

**Comment by Jotalz** [comment]
> What security reasons ? the fix is already available in UC ...

Yes you can update it yourself using that method, but mine is different and better.

**Comment by Feilink1** [comment]
@Jotalz So the repo is no longer open source or what ?? Yours is caching PDB I saw it. Idk  why you are gatekeeping common knowledge.

**Comment by Jotalz** [comment]
So why don't you update it yourself？ I haven't played it for a while and it's not my obligation to keep it updated.The main source code here, make it yourself please.

**Comment by Feilink1** [comment]
You're right you don't have the obligation to keep it updated but why do you sell it for money. I know Zen came to you and asked for the source Idk what you did exactly but he is selling it to people, that's scamming.

**Comment by Jotalz** [comment]
> You're right you don't have the obligation to keep it updated but why do you sell it for money. I know Zen came to you and asked for the source Idk what you did exactly but he is selling it to people, that's scamming.

Is that so? I never received a penny！Where did you see it for sale?

**Comment by xxZENxxx** [comment]
> You're right you don't have the obligation to keep it updated but why do you sell it for money. I know Zen came to you and asked for the source Idk what you did both say between you exactly or if he paid you but he is selling it to people, that's scamming. I am not against you I just don't know why you gatekeep.

show me proof and nice try we never share src code calm down :)

**Comment by Feilink1** [comment]
Well your friend Zen is selling it for money. Jotalz never shared the src yea but you sell the build. And stop answering I never talked to you you're not the coder you just tweak on others ppl work. You just took the advantage of the disagreement that happened between Chettoy and Jotalz to buy smth that is not yours. You can' t even code a line.

**Comment by Jotalz** [comment]
> Many features don't work properly. Can I talk to the owner @Jotalz does he have a discord ?

my discord:yisay_x

**Comment by xxZENxxx** [comment]
> Well your friend Zen is selling it for money. Jotalz never shared the src yea but you sell the build. And stop answering I never talked to you you're not the coder you just tweak on others ppl work. You just took the advantage of the disagreement that happened between Chettoy and Jotalz to buy smth that is not yours. You can' t even code a line.

send him proof bro stop cary

**Comment by Feilink1** [comment]
@xxZENxxx Tanta maghatkhod walo zaml bok ta7aja madyalk ya ji3an
