### ISSUE TITLE
如果两个敌人离得太近，你自瞄打死人后会瞬间锁定第二个人身上

### ISSUE THREAD

**Issue by litangchuanshuo** [Jotalz/apex_dma_kvm_pub#7]

**Comment by 1355499902** [comment]
如果两个敌人离得太近，你自瞄打死人后会瞬间锁定第二个人身上

**Comment by Jotalz** [comment]
> 如果两个敌人离得太近，你自瞄打死人后会瞬间锁定第二个人身上
请优先使用chettoy的版本，本fork原则上是为了给自己学习使用，出于源项目的公益性公开的。（你说的问题会考虑，但是不确定能不能应用）
