### ISSUE TITLE
it doesn't work , i don't know how to deal

### ISSUE THREAD

**Issue by QishaoUwU** [Jotalz/apex_dma_kvm_pub#9]
a@a:~/apex_dma1.29$ sudo ./apex_dma
[sudo] a password：
09:17:53 [INFO] scanning "/home/a/apex_dma1.29" for libraries
09:17:53 [INFO] adding plugin 'Connector/qemu': "/home/a/apex_dma1.29/libmemflow_qemu.so"
09:17:53 [INFO] adding plugin 'OS/win32': "/home/a/apex_dma1.29/libmemflow_win32.so"
09:17:53 [INFO] adding plugin 'Connector/kvm': "/home/a/apex_dma1.29/libmemflow_kvm.so"
inventory initialized: 0x55c35ad77890
Using kvm connector.
09:17:53 [INFO] attempting to load Connector type plugin kvm from /home/a/apex_dma1.29/libmemflow_kvm.so
09:17:53 [ERROR] connector: unable to read memory (Could not access the memflow device at /dev/memflow. Please make sure that you installed the dkms module properly and that it is loaded via modprobe memflow. Also ensure that you have read and write access to /dev/memflow. For further information check the readme at https://github.com/memflow/memflow-kvm)
09:17:53 [ERROR] connector: unable to read memory
Unable to initialize kvm connector.
Fallback to qemu connector.
09:17:53 [INFO] attempting to load Connector type plugin qemu from /home/a/apex_dma1.29/libmemflow_qemu.so
09:17:53 [INFO] qemu process with name qemu-system-x86_64 found with pid 1332
09:17:53 [INFO] qemu memory map found CTup2(7f712c000000, 17179869184)
09:17:53 [INFO] qemu process started with machine: pc-q35-6.2
09:17:53 [INFO] qemu memory map size: 400000000
09:17:53 [INFO] using fallback memory mappings for q35 with more than 2816mb of ram
09:17:53 [INFO] qemu machine mem_map: MemoryMapping: base=0 size=80000000 real_base=7f712c000000
MemoryMapping: base=100000000 size=380000000 real_base=7f71ac000000
09:17:53 [INFO] Inserting CachedPhysicalMemory middleware with size=0, validity_time=0, page_size=4096
Connector initialized: 0x55c35ae2e910
09:17:53 [INFO] attempting to load OS type plugin win32 from /home/a/apex_dma1.29/libmemflow_win32.so
09:17:53 [INFO] Building kernel of type memflow_win32::win32::kernel_builder::Win32KernelBuilder<memflow::plugins::connector::cglue_connectorinstance::cglue_internal::ConnectorInstance<cglue::boxed::CBoxcglue::trait_group::c_void, cglue::arc::CArccglue::trait_group::c_void>, memflow::plugins::connector::cglue_connectorinstance::cglue_internal::ConnectorInstance<cglue::boxed::CBoxcglue::trait_group::c_void, cglue::arc::CArccglue::trait_group::c_void>, memflow::mem::virt_translate::cache::CachedVirtualTranslate<memflow::mem::virt_translate::direct_translate::DirectTranslate, memflow::types::cache::timed_validator::TimedCacheValidator>>
09:17:53 [WARN] oslayer: not found (unable to find x64 dtb in lowstub < 1M)
09:17:53 [WARN] x64::find_lowstub() error: oslayer: not found
09:17:53 [WARN] oslayer: not found (unable to find x64 dtb in lowstub < 16M)
09:17:53 [WARN] oslayer: not found (unable to find x86_pae dtb in lowstub < 16M)
09:17:53 [WARN] oslayer: not found (unable to find x86 dtb in lowstub < 16M)
09:17:53 [WARN] oslayer: not found (unable to find aarch64 dtb in lowstub < 16M)
09:17:53 [ERROR] oslayer: not found (unable to find dtb)
09:17:53 [ERROR] oslayer: not found
09:17:53 [ERROR] oslayer: not found
unable to initialize OS
09:17:53 [INFO] inventory freed

![20240129155246](https://github.com/Jotalz/apex_dma_kvm_pub/assets/60024434/1ab595ae-7e01-45fa-8734-93f50feaaaf3)

**Comment by Jotalz** [comment]
I saw you asking the same question on chettoy‘s, so I need to confirm which version you are using.

**Comment by QishaoUwU** [comment]
> I saw you asking the same question on chettoy‘s, so I need to confirm which version you are using.

Two version have same question

**Comment by Jotalz** [comment]
If it is a question in the text,`sudo apt protobuf-compiler` , and `git submodule update --init --recursive` in apex_dma_kvm_pub,it may the reason to wrong.And in the picture,you run `apex_dma` without **`sudo`**,chettoy have mentioned it already.

**Comment by QishaoUwU** [comment]
> If it is a question in the text, , and in apex_dma_kvm_pub,it may the reason to wrong.And in the picture,you run without **`sudo`**,chettoy have mentioned it already.`sudo apt protobuf-compiler``git submodule update --init --recursive``apex_dma`

at the first line, i use "sudo./apex_dma"

**Comment by Jotalz** [comment]
You provided two different running records. I said that you did not use `sudo` in the **picture**.If this is a problem you're aware of, it shouldn't be here.Just try another solution.

**Comment by gusqing** [comment]
Recently ea seems to have taken note of kvm's many comments on uc that a ban has been issued

**Comment by Jotalz** [comment]
> Recently ea seems to have taken note of kvm's many comments on uc that a ban has been issued

Yes, I don’t know much about it at the moment. I’m not sure if it’s a detect specifically for kvm. In short, it should be used with cautions now.

**Comment by dreambeaitbos** [comment]
Why did I encounter the following error during compilation: [1%] Performing build step for 'memflow'ffi'

CMake Error at/home/pdx/apexsky/apex_dma/build/memflowEffi prefix/src/memflowEffi stamp/memflowEffi build Release. cmake: 49 (message):

Command failed: 101


'cargo', 'build', 'release'


See also


/Home/pdx/apexsky/apex_dma/build/memflow_ffi prefix/src/memflow_ffi stamp/memflow_ffi build - *. log



Gmake [2]: * * * [MakeFiles/memflow_ffi. dir/build. make: 86: memflow_ffi prefix/src/memflow_ffi stamp/memflow_ffi build] Error 1

Gmake [1]: * * * [MakeFiles/Makefile2:881: CMakeFiles/memflow_ffi. dir/all] Error 2

Gmake: * * * [Makefile: 121: all] Error 2

**Comment by Jotalz** [comment]
> Can you be more specific about how to fix that, thank you

Looks like you're missing something, try this: `sudo apt install clang`
In addition, I don’t have the energy to update at the moment. You need to update the offset part yourself.

**Comment by dreambeaitbos** [comment]
> > Can you be more specific about how to fix that, thank you
> 
> Looks like you're missing something, try this: `sudo apt install clang` In addition, I don’t have the energy to update at the moment. You need to update the offset part yourself.

Thank you, I'm going to try your method, but I don't know how to update the offset part, is there a tutorial anywhere

**Comment by Jotalz** [comment]
> > > Can you be more specific about how to fix that, thank you
> > 
> > 
> > Looks like you're missing something, try this: `sudo apt install clang` In addition, I don’t have the energy to update at the moment. You need to update the offset part yourself.
> 
> Thank you, I'm going to try your method, but I don't know how to update the offset part, is there a tutorial anywhere

If you get the dump file(Text similar to offsets.txt in the project) by others, just read the Update OFFSETS section in  readme.Then manually update the offset named HIGHLIGHT_SETTINGS in offsets.h,No matter how you get it.

**Comment by dreambeaitbos** [comment]
> > > > Can you be more specific about how to fix that, thank you
> > > 
> > > 
> > > Looks like you're missing something, try this: `sudo apt install clang` In addition, I don’t have the energy to update at the moment. You need to update the offset part yourself.
> > 
> > 
> > Thank you, I'm going to try your method, but I don't know how to update the offset part, is there a tutorial anywhere
> 
> If you get the dump file(Text similar to offsets.txt in the project) by others, just read the Update OFFSETS section in readme.Then manually update the offset named HIGHLIGHT_SETTINGS in offsets.h,No matter how you get it.

Thank you for your reply. You are really a good person. Please allow me to express my gratitude. I really like you, but after following your instructions and installing the clang, it still prompts the same error.

**Comment by Jotalz** [comment]
> > > > > Can you be more specific about how to fix that, thank you
> > > > 
> > > > 
> > > > Looks like you're missing something, try this: `sudo apt install clang` In addition, I don’t have the energy to update at the moment. You need to update the offset part yourself.
> > > 
> > > 
> > > Thank you, I'm going to try your method, but I don't know how to update the offset part, is there a tutorial anywhere
> > 
> > 
> > If you get the dump file(Text similar to offsets.txt in the project) by others, just read the Update OFFSETS section in readme.Then manually update the offset named HIGHLIGHT_SETTINGS in offsets.h,No matter how you get it.
> 
> Thank you for your reply. You are really a good person. Please allow me to express my gratitude. I really like you, but after following your instructions and installing the clang, it still prompts the same error.

What is the error reported this time? Have you installed all other Dependencies and RUST according to the tutorial?

**Comment by dreambeaitbos** [comment]
> > > > > > Can you be more specific about how to fix that, thank you
> > > > > 
> > > > > 
> > > > > Looks like you're missing something, try this: `sudo apt install clang` In addition, I don’t have the energy to update at the moment. You need to update the offset part yourself.
> > > > 
> > > > 
> > > > Thank you, I'm going to try your method, but I don't know how to update the offset part, is there a tutorial anywhere
> > > 
> > > 
> > > If you get the dump file(Text similar to offsets.txt in the project) by others, just read the Update OFFSETS section in readme.Then manually update the offset named HIGHLIGHT_SETTINGS in offsets.h,No matter how you get it.
> > 
> > 
> > Thank you for your reply. You are really a good person. Please allow me to express my gratitude. I really like you, but after following your instructions and installing the clang, it still prompts the same error.
> 
> What is the error reported this time? Have you installed all other Dependencies and RUST according to the tutorial?

Yes, I installed everything according to the prompts, but when I enter the/. build. sh command, an error message will appear
pdx@pdx-desktop :~/apexsky/apex_dma $/ Build.sh

+Set - eo pipefail

+Cargo -- version

Cargo 1.75.0

+++Dirname/ Build.sh

++CD

++Pwd

+SCRIPT-DIR=/home/pdx/apexsky/apex_dma

+BUILL_DIR=/home/pdx/apexsky/apex_dma/build

+Mkdir - p/home/pdx/apexsky/apex_dma/build

+Cd/home/pdx/apexsky/apex_dma/lib/memflow kvm

+Set+e

+Make

Touch "/home/pdx/apexsky/apex_dma/lib/memflow kvm/build/Makefile"

/Home/pdx/apexsky/apex_dma/lib/memflow kvm/build

Make C/lib/modules/6.2.0-39 generic/build M=/home/pdx/apexsky/apex_dma/lib/memflow kvm/build src=/home/pdx/apexsky/apex_dma/lib/memflow kvm/memflow kmod modules

Make [1]: Enter the directory "/usr/src/Linux headers 6.2.0-39 generic"

Warning: The compiler buffers from the one used to build the kernel

The kernel was built by: x86_64 Linux gnu gcc-11 (Ubuntu 11.4.0-1ubuntu1-22.04) 11.4.0

You are using: gcc-11 (Ubuntu 11.4.0-1ubuntu1-22.04) 11.4.0

Make [1]: Leave directory "/usr/src/Linux headers 6.2.0-39 generic"
Warning: The compiler buffers from the one used to build the kernel

The kernel was built by: x86_64 Linux gnu gcc-11 (Ubuntu 11.4.0-1ubuntu1-22.04) 11.4.0

You are using: gcc-11 (Ubuntu 11.4.0-1ubuntu1-22.04) 11.4.0

Make [1]: Leave directory "/usr/src/Linux headers 6.2.0-39 generic"

+Cp/home/pdx/apexsky/apex_dma/lib/memflow kvm/build/memflow.ko/home/pdx/apexsky/apex_dma/build/

+Set - e

+Cd/home/pdx/apexsky/apex_dma/apexsky

+Cargo build -- release

Warning: variant 'Reset' is not constructed

-->Src/menu/mod.rs: 43:5

|

37 | enum Message{

|------ variant in this enum

43 | Reset,

|^^^^^

|

=Note: ` # [warn (dead_code)] ` on by default


Warning: 'apexsky' (lib) generated 1 warning

Finished release [optimized] target (s) in 0.69s

+Cd/home/pdx/apexsky/apex_dma

+Cd/home/pdx/apexsky/apex_dma/build

+Cmake

--Including Wayland support

--Configuring done

--Generating done

--Build files have been written to:/home/pdx/apexsky/apex_dma/
+Cmake -- build

[1%] Performing build step for 'memflow'ffi'

CMake Error at/home/pdx/apexsky/apex_dma/build/memflowEffi prefix/src/memflowEffi stamp/memflowEffi build Release. cmake: 49 (message):

Command failed: 101


'cargo', 'build', 'release'


See also


/Home/pdx/apexsky/apex_dma/build/memflow_ffi prefix/src/memflow_ffi stamp/memflow_ffi build - *. log



Gmake [2]: * * * [MakeFiles/memflow_ffi. dir/build. make: 86: memflow_ffi prefix/src/memflow_ffi stamp/memflow_ffi build] Error 1

Gmake [1]: * * * [MakeFiles/Makefile2:881: CMakeFiles/memflow_ffi. dir/all] Error 2

Gmake: * * * [Makefile: 121: all] Error 2
